apiVersion: v1
kind: Service
metadata:
  name: message-svc
spec:
  selector:
    role: app
  ports:
    #port to forwart to inside the pod
    - targetport: 80
      #port accessible inside cluster
      port: 80
      #port accessible outside cluster
      nodePort: 32000
  type: LoadBalancer