apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  labels:
    role: app
spec:
  replicas: 5
  selector:
    matchLabels:
      role: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1    
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: {{ image_id }}
        resources:
          requests:
            cpu: 10m